### ISSUE TITLE
User story: Open a post

### ISSUE THREAD

**Issue by lienebriede** [lienebriede/jurtaka#11]
As a **New Site User** I can **open a post** so that **I can read the full post and the comments**

## Acceptance Criteria:

- I can open a post and see its full text
- I can exit the post and return to the post list

## Tasks:

- [x] Add a view for an individual post
- [x] Add a template, style
- [x] Add a back button, style
