### ISSUE TITLE
User story: User registration and log in

### ISSUE THREAD

**Issue by lienebriede** [lienebriede/jurtaka#13]
As a **New Site User** I can **register an account** so that **I can interact with the forum**

## Acceptance Criteria:

- I can register an account
- I can log in and log out of my account
- There is a message that informs me wether I am logged in or not
- I find the log in button easily

## Tasks:

- [x] Add authentication
- [x] Modify templates for authentication
- [x] Add a message on forum page that a user is/is not logged in
- [x] Style templates and log in/out buttons in navbar
