### ISSUE TITLE
User story: Add posts

### ISSUE THREAD

**Issue by lienebriede** [lienebriede/jurtaka#17]
As a **Registered Site User** I can **write posts** so that **I can engage with the forum**

## Acceptance Criteria:

- I can see a "add a post" section
- I can add posts
- After posting I am redirected back to the main site
- After posting I receive a message that my post is awaiting approval

## Tasks:

- [x] Create a section and link to Add post
- [x] Create a form
- [x] Create a template
- [x] Add Django messaging
- [x] Add to templates, style
