### ISSUE TITLE
User story: Search forum

### ISSUE THREAD

**Issue by lienebriede** [lienebriede/jurtaka#24]
As a **New Site User** I can **search the forum** so that **I can find posts on topics that I am interested in**

## Acceptance Criteria:

- I can find a search bar on the site
- I can type words in the search bar and it returns posts that contain them
- If the words do not match I get a message saying that nothing was found

## Tasks:

- [x] Add a search bar in navbar, style
- [x] Add filtering by searching to views, update urls
- [x] Modify templates, style

**Comment by lienebriede** [comment]
Bug: Comment count does not appear in search result template
