### ISSUE TITLE
User story: Edit and delete comments

### ISSUE THREAD

**Issue by lienebriede** [lienebriede/jurtaka#26]
As a **Registered Site User** I can **edit and delete my comment** so that **I can update content of my comment or remove comments that are not relevant**

## Acceptance Criteria:

- After submitting a comment, I,  as the comment author, can see options to delete and update my comment
- When I click the delete option, a confirmation prompt appears
- Upon deleting or editing my comment, a success message is displayed

## Tasks:

- [ ] Create views and modify urls
- [ ] Update templates
- [ ] Add buttons, style
- [ ] Add JavaScript logic
