### ISSUE TITLE
User story: Edit and delete posts

### ISSUE THREAD

**Issue by lienebriede** [lienebriede/jurtaka#27]
As a **Registered Site User** I can **update and delete my posts** so that **I can update the content of my post or remove posts that are not relevant**

## Acceptance Criteria:

- After submitting a post, as the post author, I can see an option to update my post
- I can either update the content of my post or delete my post entirely
- Upon deleting my post, I get a confirmation prompt that asks to confirm the deletion of my post

## Tasks:

- [x] Create views and modify urls
- [x] Create a template for editing post
- [x] Update templates
- [x] Add buttons, style
- [x] Add JavaScript confirmation prompt
