### ISSUE TITLE
User story: Manage About site

### ISSUE THREAD

**Issue by lienebriede** [lienebriede/jurtaka#28]
As a **Site Admin** I can **manage the content on the About site** so that **I can provide up to date information to users**

## Acceptance Criteria:

- I can find the About page on the admin panel
- I can manage the text of the page
- I can style the text directly in the admin panel

## Tasks:

- [x] Create a new app and a About model, register
- [x] Create views and urls
- [x] Modify templates
- [x] Add Summernote to enhance the admin panel
