### ISSUE TITLE
User story: Contact site administration

### ISSUE THREAD

**Issue by lienebriede** [lienebriede/jurtaka#30]
As a **Registered/Unregistered Site User** I can **fill in the contact form** so that **I can contact the forum administration**

## Acceptance Criteria:

- I can find a contact form on the site
- I can fill in the form and send it to the admin
- After sending the form, I receive a message that the form has been sent
- I can choose a reason for contacting the admin

## Tasks:

- [x] Add a Contact model
- [x] Add views and update urls
- [x] Create a template, style
