### ISSUE TITLE
User story: Receive contact request

### ISSUE THREAD

**Issue by lienebriede** [lienebriede/jurtaka#31]
As a **Site Admin** I can **receive contact requests** so that **I can respond to user inquiries and manage communication efficiently**

## Acceptance Criteria:

- I can receive contact requests from both registered and unregistered users
- I can see what is the reason of the request

## Tasks:

- [x] Add functionality that both registered and unregistered users can contact the site admin
- [x] Add functionality that logged in users do not require to give an email, but unregistered users do
- [x] Add a reason field to the form
- [x] Add status to contacts so it is easier to manage for the admin

**Comment by lienebriede** [comment]
Problems:
1. Error on the site for the username field: Select a valid choice. That choice is not one of the available choices.
2. Username has to appear automatically in the username field
3. Error in models, does not allow to add the reasons field.
