### ISSUE TITLE
User story: CRUD operations Forum app

### ISSUE THREAD

**Issue by lienebriede** [lienebriede/jurtaka#7]
As a **Site Admin** I can **create, read, update and delete data** so that **I can manage the content of the forum site**

## Acceptance Criteria:

- I can create, read, update and delete data on the main forum site (posts, comments, likes etc.)
- I can approve and disapprove posts that are posted by users
- I quickly understand the data in the database

## Tasks:

- [x] Set up forum app
- [x] Create and register Post model
- [x] Create and register Comment model
- [x] Create and register Like model
- [x] Create and register Tag model
- [x] Create string representation to objects
- [x] Test
